name: Deploy to Shuttle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Shuttle CLI
        run: cargo install shuttle-launcher --locked
      - name: Run tests
        run: cargo test --all
      - name: Lint
        run: cargo clippy --all -- -D warnings
      - name: Deploy to Shuttle
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
        run: shuttle deploy